name: LaTeX build
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: report
          latexmk_shell_escape: true
      - uses: actions/upload-artifact@v2
        with:
          name: fys2085-report
          path: report/main.pdf
          if-no-files-found: error
